---
- name: Install & run docker
  hosts: web
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Install the required packages and update the package cache
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker’s official GPG key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the repository 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present 

    - name: Install docker engine and update the package cache
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
      - Restart Docker

    - name: Add  user 'ubunu' to  the group 'docker'
      user:
       name: ubuntu
       groups: docker 
       append: yes

    - name: Run Docker
      shell: docker run -d -p 8080:80 nginx

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted



